spring:
  application:
    name: Processor Service


  kafka:
    bootstrap-servers: localhost:29092
    schema-registry:
      url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 10
      properties:
        enable:
          idempotence: false
        min:
          insync:
            replicas: 1
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
        delivery:
          timeout:
            ms: 120000
        retry:
          backoff:
            ms: 1000
    consumer:
      bootstrap-servers: localhost:29092
      schema-registry:
        url: http://localhost:8081
      group-id: processor-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        json-trusted-packages: '"*"'

app:
  kafka:
    telemetry:
      topics:
        raw: uav-telemetry-raw
        processed: uav-telemetry-processed
        alert: uav-telemetry-alert