server:
  port: 8087

spring:
  application.name: Ingest Service
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      retries: 10
      properties:
        enable:
          idempotence: true
        min:
          insync:
            replicas: 2
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
        delivery:
          timeout:
            ms: 120000
        retry:
          backoff:
            ms: 1000

