import org.gradle.api.Plugin

plugins {
	id 'java'
    id 'maven-publish'
    id 'com.github.davidmc24.gradle.plugin.avro' version '1.9.1'
}

group = 'org.mdanylko.uav.schema-registry'
version = '0.0.1-SNAPSHOT'
description = 'schema-registry'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
    mavenLocal()
	mavenCentral()
}

dependencies {
// Source: https://mvnrepository.com/artifact/org.apache.avro/avro
    implementation 'org.apache.avro:avro:1.12.1'
}

tasks.named('jar') {
    enabled = true
}

tasks.withType(JavaCompile).configureEach {
    dependsOn tasks.named("generateAvroJava")
}

tasks.named("generateAvroJava") {
    source(file("/src/main/resources/avro"))
    outputDir = file("$buildDir/generated-sources/avro")

    stringType = "String"
    createSetters = false
    enableDecimalLogicalType = true
    fieldVisibility = "PRIVATE"
}

sourceSets {
    main {
        java {
            srcDir "$buildDir/generated-sources/avro"
        }
    }
}

// Publish jar to local .m2
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.group
            artifactId = project.name
            version = project.version

            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
        }
    }
    repositories {
        mavenLocal()
    }
}

