plugins {
    id 'java'
    id 'maven-publish'
}

group = 'org.mdanylko.uav.core'
version = '0.0.1-SNAPSHOT'
description = 'core'

tasks.named('jar') {
    enabled = true
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

tasks.named('jar') {
    enabled = true
}

// `core/build.gradle`
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.group
            artifactId = project.name
            version = project.version

            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
        }
    }
    repositories {
        mavenLocal()
    }
}